package customerrors

const (


	//Common errors
	ERR_INVALID_REQUEST = "ERR_INVALID_REQUEST"
	ERR_INTERNAL_SERVER_ERROR = "ERR_INTERNAL_SERVER_ERROR"
	ERR_UNAUTHORIZED = "ERR_UNAUTHORIZED"
	ERR_FORBIDDEN = "ERR_FORBIDDEN"
	ERR_NOT_FOUND = "ERR_NOT_FOUND"
	ERR_CONFLICT = "ERR_CONFLICT"
	ERR_BAD_REQUEST = "ERR_BAD_REQUEST"
	ERR_UNPROCESSABLE_ENTITY = "ERR_UNPROCESSABLE_ENTITY"
	ERR_TOO_MANY_REQUESTS = "ERR_TOO_MANY_REQUESTS"
	ERR_SERVICE_UNAVAILABLE = "ERR_SERVICE_UNAVAILABLE"
	ERR_GATEWAY_TIMEOUT = "ERR_GATEWAY_TIMEOUT"
	ERR_REQUEST_TIMEOUT = "ERR_REQUEST_TIMEOUT"
	ERR_PAYLOAD_TOO_LARGE = "ERR_PAYLOAD_TOO_LARGE"
	ERR_VALIDATION_FAILED = "ERR_VALIDATION_FAILED"
	ERR_INVALID_CREDENTIALS = "ERR_INVALID_CREDENTIALS"
	ERR_INVALID_TOKEN = "ERR_INVALID_TOKEN"
	ERR_EXPIRED_TOKEN = "ERR_EXPIRED_TOKEN"
	ERR_INVALID_REFRESH_TOKEN = "ERR_INVALID_REFRESH_TOKEN"
	ERR_EXPIRED_REFRESH_TOKEN = "ERR_EXPIRED_REFRESH_TOKEN"
	ERR_GRPC_ERROR = "ERR_GRPC_ERROR"
	ERR_INVALID_RESPONSE ="ERR_INVALID_RESPONSE"
		

	// RegisterUser errors
	ERR_REG_PASSWORD_MISMATCH = "ERR_REG_PASSWORD_MISMATCH"
	ERR_REG_INVALID_EMAIL     = "ERR_REG_INVALID_EMAIL"
	ERR_REG_INVALID_PASSWORD  = "ERR_REG_INVALID_PASSWORD"
	ERR_REG_CREATION_FAILED   = "ERR_REG_CREATION_FAILED"

	// LoginUser errors
	ERR_LOGIN_CRED_CHECK_FAILED = "ERR_LOGIN_CRED_CHECK_FAILED"
	ERR_LOGIN_USER_NOT_FOUND    = "ERR_LOGIN_USER_NOT_FOUND"
	ERR_LOGIN_BAN_CHECK_FAILED  = "ERR_LOGIN_BAN_CHECK_FAILED"
	ERR_LOGIN_ACCOUNT_BANNED    = "ERR_LOGIN_ACCOUNT_BANNED"
	ERR_LOGIN_CRED_WRONG        = "ERR_LOGIN_CRED_WRONG"
	ERR_LOGIN_2FA_CHECK_FAILED  = "ERR_LOGIN_2FA_CHECK_FAILED"
	ERR_LOGIN_2FA_CODE_INVALID  = "ERR_LOGIN_2FA_CODE_INVALID"
	ERR_LOGIN_NOT_VERIFIED      = "ERR_LOGIN_NOT_VERIFIED"
	ERR_LOGIN_TOKEN_GEN_FAILED  = "ERR_LOGIN_TOKEN_GEN_FAILED"
	ERR_GOOGLE_TOKEN_INVALID = "ERR_GOOGLE_TOKEN_INVALID"

	// LoginAdmin errors
	ERR_ADMIN_LOGIN_CRED_CHECK_FAILED = "ERR_ADMIN_LOGIN_CRED_CHECK_FAILED"
	ERR_ADMIN_LOGIN_NOT_FOUND         = "ERR_ADMIN_LOGIN_NOT_FOUND"
	ERR_ADMIN_LOGIN_NO_PRIVILEGES     = "ERR_ADMIN_LOGIN_NO_PRIVILEGES"
	ERR_ADMIN_LOGIN_CRED_WRONG        = "ERR_ADMIN_LOGIN_CRED_WRONG"
	ERR_ADMIN_LOGIN_NOT_VERIFIED      = "ERR_ADMIN_LOGIN_NOT_VERIFIED"
	ERR_ADMIN_LOGIN_TOKEN_FAILED      = "ERR_ADMIN_LOGIN_TOKEN_FAILED"

	// TokenRefresh errors
	ERR_TOKEN_REFRESH_INVALID = "ERR_TOKEN_REFRESH_INVALID"
	ERR_TOKEN_REFRESH_FAILED  = "ERR_TOKEN_REFRESH_FAILED"

	// ResendEmailVerification errors
	ERR_EMAIL_RESEND_FAILED = "ERR_EMAIL_RESEND_FAILED"

	// VerifyUser errors
	ERR_VERIFY_CHECK_FAILED  = "ERR_VERIFY_CHECK_FAILED"
	ERR_VERIFY_TOKEN_INVALID = "ERR_VERIFY_TOKEN_INVALID"

	// ForgotPassword errors
	ERR_PW_FORGOT_INVALID_EMAIL = "ERR_PW_FORGOT_INVALID_EMAIL"
	ERR_PW_FORGOT_INIT_FAILED   = "ERR_PW_FORGOT_INIT_FAILED"

	// FinishForgotPassword errors
	ERR_PW_RESET_MISMATCH        = "ERR_PW_RESET_MISMATCH"
	ERR_PW_RESET_INVALID_PASSWORD = "ERR_PW_RESET_INVALID_PASSWORD"

	// ChangePassword errors
	ERR_PW_CHANGE_MISMATCH        = "ERR_PW_CHANGE_MISMATCH"
	ERR_PW_CHANGE_INVALID_PASSWORD = "ERR_PW_CHANGE_INVALID_PASSWORD"

	// UpdateProfile errors
	ERR_PROFILE_UPDATE_FAILED = "ERR_PROFILE_UPDATE_FAILED"

	// UpdateProfileImage errors
	ERR_PROFILE_IMAGE_UPDATE_FAILED = "ERR_PROFILE_IMAGE_UPDATE_FAILED"

	// CheckBanStatus errors
	ERR_BAN_STATUS_CHECK_FAILED = "ERR_BAN_STATUS_CHECK_FAILED"
	ERR_BAN_STATUS_NOT_FOUND    = "ERR_BAN_STATUS_NOT_FOUND"

	// FollowUser errors
	ERR_FOLLOW_ACTION_FAILED = "ERR_FOLLOW_ACTION_FAILED"

	// UnfollowUser errors
	ERR_UNFOLLOW_ACTION_FAILED = "ERR_UNFOLLOW_ACTION_FAILED"

	// GetFollowing errors
	ERR_FOLLOWING_LIST_FAILED = "ERR_FOLLOWING_LIST_FAILED"

	// GetFollowers errors
	ERR_FOLLOWERS_LIST_FAILED = "ERR_FOLLOWERS_LIST_FAILED"

	// CreateUserAdmin errors
	ERR_ADMIN_CREATE_PASSWORD_MISMATCH = "ERR_ADMIN_CREATE_PASSWORD_MISMATCH"
	ERR_ADMIN_CREATE_INVALID_EMAIL     = "ERR_ADMIN_CREATE_INVALID_EMAIL"
	ERR_ADMIN_CREATE_INVALID_PASSWORD  = "ERR_ADMIN_CREATE_INVALID_PASSWORD"
	ERR_ADMIN_CREATE_FAILED            = "ERR_ADMIN_CREATE_FAILED"

	// UpdateUserAdmin errors
	ERR_ADMIN_UPDATE_CHECK_FAILED     = "ERR_ADMIN_UPDATE_CHECK_FAILED"
	ERR_ADMIN_UPDATE_NO_PRIVILEGES    = "ERR_ADMIN_UPDATE_NO_PRIVILEGES"
	ERR_ADMIN_UPDATE_INVALID_PASSWORD = "ERR_ADMIN_UPDATE_INVALID_PASSWORD"
	ERR_ADMIN_UPDATE_FAILED           = "ERR_ADMIN_UPDATE_FAILED"

	// BanUser errors
	ERR_BAN_USER_FAILED = "ERR_BAN_USER_FAILED"

	// UnbanUser errors
	ERR_UNBAN_USER_FAILED = "ERR_UNBAN_USER_FAILED"

	// VerifyAdminUser errors
	ERR_ADMIN_VERIFY_FAILED = "ERR_ADMIN_VERIFY_FAILED"

	// UnverifyUser errors
	ERR_ADMIN_UNVERIFY_FAILED = "ERR_ADMIN_UNVERIFY_FAILED"

	// SoftDeleteUserAdmin errors
	ERR_ADMIN_DELETE_CHECK_FAILED  = "ERR_ADMIN_DELETE_CHECK_FAILED"
	ERR_ADMIN_DELETE_NO_PRIVILEGES = "ERR_ADMIN_DELETE_NO_PRIVILEGES"
	ERR_ADMIN_DELETE_FAILED        = "ERR_ADMIN_DELETE_FAILED"

	// GetAllUsers errors
	ERR_USERS_LIST_FAILED = "ERR_USERS_LIST_FAILED"

	// BanHistory errors
	ERR_BAN_HISTORY_FAILED = "ERR_BAN_HISTORY_FAILED"

	// SearchUsers errors
	ERR_USERS_SEARCH_FAILED = "ERR_USERS_SEARCH_FAILED"

	// SetUpTwoFactorAuth errors
	ERR_2FA_SETUP_FAILED = "ERR_2FA_SETUP_FAILED"

	// DisableTwoFactorAuth errors
	ERR_2FA_DISABLE_CHECK_FAILED = "ERR_2FA_DISABLE_CHECK_FAILED"
	ERR_2FA_DISABLE_CRED_WRONG   = "ERR_2FA_DISABLE_CRED_WRONG"
	ERR_2FA_DISABLE_FAILED       = "ERR_2FA_DISABLE_FAILED"

	// GetTwoFactorAuthStatus errors
	ERR_2FA_STATUS_CHECK_FAILED = "ERR_2FA_STATUS_CHECK_FAILED"

	// Repository-specific errors
	ERR_PARAM_EMPTY                    = "ERR_PARAM_EMPTY"
	ERR_USER_NOT_FOUND                 = "ERR_USER_NOT_FOUND"
	ERR_CRED_CHECK_FAILED              = "ERR_CRED_CHECK_FAILED"
	ERR_CRED_WRONG                     = "ERR_CRED_WRONG"
	ERR_ADMIN_NOT_CONFIGURED           = "ERR_ADMIN_NOT_CONFIGURED"
	ERR_PROFILE_NOT_FOUND              = "ERR_PROFILE_NOT_FOUND"
	ERR_BAN_UPDATE_FAILED              = "ERR_BAN_UPDATE_FAILED"
	ERR_2FA_ALREADY_ENABLED            = "ERR_2FA_ALREADY_ENABLED"
	ERR_2FA_NOT_ENABLED                = "ERR_2FA_NOT_ENABLED"
	ERR_2FA_CODE_INVALID               = "ERR_2FA_CODE_INVALID"
	ERR_VERIFICATION_ALREADY_EXISTS    = "ERR_VERIFICATION_ALREADY_EXISTS"
	ERR_ALREADY_VERIFIED               = "ERR_ALREADY_VERIFIED"
	ERR_TOKEN_CREATION_FAILED          = "ERR_TOKEN_CREATION_FAILED"
	ERR_TOKEN_VERIFICATION_FAILED      = "ERR_TOKEN_VERIFICATION_FAILED"
	ERR_PASSWORD_HASH_FAILED           = "ERR_PASSWORD_HASH_FAILED"
	ERR_NO_EXISTING_PASSWORD           = "ERR_NO_EXISTING_PASSWORD"
)